# Generated by Django 5.0.6 on 2026-05-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='scraped_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='scraper_source',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
    ]
