# Generated by Django 5.0.6 on 2026-05-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submission_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
