# Generated by Django 5.0.6 on 2026-04-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], max_length=2)),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20)),
                ('category', models.CharField(choices=[('use_ai', 'Usar IA'), ('code_with_ai', 'Programar con IA'), ('ml_fundamentals', 'Fundamentos de ML'), ('deep_learning', 'Deep Learning'), ('data_science', 'Ciencia de datos'), ('ai_tools', 'Herramientas de IA'), ('agents', 'Agentes y automatización'), ('ethics_ai', 'Ética en IA')], max_length=50)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('community', 'Comunidad')], default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
